### ISSUE TITLE
Why remove isValid from v2?

### ISSUE THREAD

**Issue by mihaiblaga89** [niradler/tracking-number-validation#4]

**Comment by niradler** [comment]
due to the similarity sometimes there is a match for more then 1 courier, in v2  to emphasis this issue, api function was slightly change.
you can now use isCourier, the same why you use isValid.
if this is an issue please let me know and i will add isValid with an //not-safe flag like i added getCourierOne.

**Comment by niradler** [comment]
@mihaiblaga89 isValid Added.
Thanks for pointing it out!

**Comment by mihaiblaga89** [comment]
Thanks.
